site_name: Shopping Cart
site_description: A sample project that implements a few vertical slices of a shopping cart event model using event sourcing.
site_author: Moritz E. Beber
site_url: https://shopping-cart.readthedocs.io/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
      default_handler: python
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Midnighter
      name: Moritz E. Beber

copyright: Copyright &copy 2025 Moritz E. Beber

repo_url: https://github.com/Midnighter/shopping-cart
repo_name: Midnighter/shopping-cart

watch:
  - src/shopping_cart
